### ISSUE TITLE
Revised Rust version not using function test_ray

### ISSUE THREAD

**Issue by jzakiya** [edin/raytracer#15]
In going over the revised Rust version from a couple of days ago, the compiler says ``test_ray`` function not used, though the image does not appear affected because of it.

```
    fn test_ray(&self, ray: &Ray) -> Option<f32>
    {
        let intersect = self.intersections(ray);
        return match intersect {
            Some(result) => Some(result.dist),
            None => None
        }
    }
```
In the Ruby, Crystal, et al version it was used in

```
  def addLight(col, light, pos, norm, scene, thing, rd)
    ldis  = Vector.minus(light.pos, pos)
    livec = Vector.norm(ldis)
    neatIsect = self.testRay(Ray.new(pos, livec), scene)
   ...
 end
```
In Nim as

```
func getNaturalColor(scene: Scene, sp: SurfaceProperties,
  pos, rd, norm: Vector): Color =
  var rdNorm = rd.norm()
  for light in scene.lights:
    let
      ldis = light.pos - pos
      ldisLen = ldis.len()
      livec = ldis.norm()
      neatIsect = scene.testRay(pos, livec)
      ...
```

**Comment by edin** [comment]
It's updated now and the rest of the warnings related to the naming convention are fixed.

**Comment by jzakiya** [comment]
Great!! 
I tried to fix it, but see you had to make 2 changes to make it work.  Confirmed it creates correct image.

I was waiting on the fix before I submit a PR of tweaks that make it slightly faster and simpler, but will now.

**Comment by jzakiya** [comment]
Unless you feel otherwise, I'll just close this since you've resolved the issue that was raised.
